I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1, in script
    ﻿init python:
  File "game/script.rpy", line 1, in script
    ﻿init python:
  File "game/script.rpy", line 2, in <module>
    import compression
IOError: [Errno 2] No such file or directory: u'C:\\Users\\rafae\\Desktop\\renpy-7.4.11-sdk\\images/images.zip'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 1, in script
    ﻿init python:
  File "game/script.rpy", line 1, in script
    ﻿init python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 2, in <module>
    import compression
  File "renpy/loader.py", line 985, in load_module
    exec(code, mod.__dict__)
  File "compression.py", line 25, in <module>
  File "compression.py", line 20, in images
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/zipfile.py", line 779, in __init__
IOError: [Errno 2] No such file or directory: u'C:\\Users\\rafae\\Desktop\\renpy-7.4.11-sdk\\images/images.zip'

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Invasao_urbana 1.0
Mon Jun  6 22:30:10 2022
